name: Make Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd dashboard
        npm ci
        npm run build
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: "release-${{ GITHUB_REF }}.zip"
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifact: "release-${{ GITHUB_REF }}.zip"
        allowUpdates: true
        prerelease: true
        artifactContentType: "application/zip"
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
    
